/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import db.DBManager;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NoWay
 */
public class ModeratorFrame extends javax.swing.JFrame {

    /**
     * Creates new form ModeratorFrame
     */
     DBManager DB;
    String user_id;
    String[] Mycolumns=new String [] {
                "ID", "Title", "Description", "Price", "Status", "Date", "Username"};
    String[] UnclaiColumns=new String [] {
                "ID", "Title", "Description", "Price", "Date", "Username"};
    public ModeratorFrame(DBManager DB, String user_id) {
        this.setTitle("Username" +" "+ user_id);
        this.DB=DB;
        this.user_id = user_id;
        initComponents();
        this.populate_myAdvertisements_table(); // All the user 
        this.populate_UnclAdvertisements_table(); // All the user AddAdvertisement
        populate_category_typess();

    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdvMode_panel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ModerUnclaim_table = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox<>();
        ModeSerch_textBox = new javax.swing.JTextField();
        claim_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        categ_comb_idd = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ModerMy_table = new javax.swing.JTable();
        approve_button = new javax.swing.JButton();
        disapprove_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AdvMode_panel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        ModerUnclaim_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Description", "Price", "Date", "Username"
            }
        ));
        jScrollPane1.setViewportView(ModerUnclaim_table);

        jComboBox2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Last 1 Months", "Last 3 Months", "Last 6 Months" }));

        ModeSerch_textBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ModeSerch_textBoxKeyReleased(evt);
            }
        });

        claim_button.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        claim_button.setText("Claim");
        claim_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claim_buttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Category");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Period ");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Title, Description");

        categ_comb_idd.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        categ_comb_idd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categ_comb_iddActionPerformed(evt);
            }
        });
        categ_comb_idd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                categ_comb_iddKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(categ_comb_idd, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ModeSerch_textBox, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(claim_button, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(claim_button, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ModeSerch_textBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categ_comb_idd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        AdvMode_panel.addTab("Unclaimed Advertisments  ", jPanel1);

        ModerMy_table.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ModerMy_table.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ModerMy_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Description", "Price", "Status", "Date", "Userbane"
            }
        ));
        jScrollPane2.setViewportView(ModerMy_table);

        approve_button.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        approve_button.setText("Approve");
        approve_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approve_buttonActionPerformed(evt);
            }
        });

        disapprove_button.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        disapprove_button.setText("Disapprove");
        disapprove_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disapprove_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(approve_button, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(disapprove_button, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disapprove_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(approve_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        AdvMode_panel.addTab("My Advertisments  ", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdvMode_panel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(AdvMode_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void claim_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claim_buttonActionPerformed
        // TODO add your handling code here:
        int row = this.ModerUnclaim_table.getSelectedRow();
        boolean result=false;
        if(row>=0){
            String advertisement_id=(String)ModerUnclaim_table.getValueAt(row, 0);
            result=DB.ClaimAdvertisement(advertisement_id, user_id);
        }
        
        if(result){
             JOptionPane.showMessageDialog(this,
    "The advertisement was claimed correctly",
    "Confirmation",
    JOptionPane.INFORMATION_MESSAGE);
        }
        populate_UnclAdvertisements_table();
        populate_myAdvertisements_table();
        
        
        
    }//GEN-LAST:event_claim_buttonActionPerformed

    
    
    
    private void populate_category_typess(){
        LinkedList<DBManager.Record> Category_types=DB.getCategoryTypes();
        this.categ_comb_idd.removeAllItems();
        for(DBManager.Record Category_type:Category_types){
            this.categ_comb_idd.addItem(Category_type);
        }
        
    }
    
    private void approve_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approve_buttonActionPerformed
        // TODO add your handling code here:
        
        int row = this.ModerMy_table.getSelectedRow();
        boolean result=false;
        if(row>=0){
            String advertisement_id=(String)ModerMy_table.getValueAt(row, 0);
            result=DB.ApprovAdvertisement(advertisement_id);
        }
        
        if(result){
             JOptionPane.showMessageDialog(this,
    "The advertisement was approved correctly",
    "Confirmation",
    JOptionPane.INFORMATION_MESSAGE);
        }
        populate_myAdvertisements_table();
        
    }//GEN-LAST:event_approve_buttonActionPerformed

    private void ModeSerch_textBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ModeSerch_textBoxKeyReleased
        // TODO add your handling code here:
        Object[][] accounts_data=DB.getModraSerchAdvertisements(this.ModeSerch_textBox.getText());
        this.ModerUnclaim_table.setModel(new DefaultTableModel(accounts_data,UnclaiColumns));
    }//GEN-LAST:event_ModeSerch_textBoxKeyReleased

    private void disapprove_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disapprove_buttonActionPerformed
        // TODO add your handling code here:
        
        int row = this.ModerMy_table.getSelectedRow();
        boolean result=false;
        if(row>=0){
            String advertisement_id=(String)ModerMy_table.getValueAt(row, 0);
            result=DB.DisapprovAdvertisement(advertisement_id);
        }
        
        if(result){
             JOptionPane.showMessageDialog(this,
    "The advertisement was disapproved correctly",
    "Confirmation",
    JOptionPane.INFORMATION_MESSAGE);
        }
        populate_myAdvertisements_table();
    }//GEN-LAST:event_disapprove_buttonActionPerformed

    private void categ_comb_iddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categ_comb_iddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categ_comb_iddActionPerformed

    private void categ_comb_iddKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_categ_comb_iddKeyReleased
        // TODO add your handling code here:
        String type =this.categ_comb_idd.getSelectedItem().toString();
        
    }//GEN-LAST:event_categ_comb_iddKeyReleased

    /**
     * @param args the command line arguments
     */
    
    
     public void populate_myAdvertisements_table(){
    Object[][] advertisements_data=DB.getMyAdvertisements_Moder(user_id);
    this.ModerMy_table.setModel(new DefaultTableModel(advertisements_data,Mycolumns));
    /**
     * @param args the command line arguments
     */
  
    
    }
    public void populate_UnclAdvertisements_table(){
    Object[][] advertisements_data=DB.getUnclaimAdvertisements_Moder();
    this.ModerUnclaim_table.setModel(new DefaultTableModel(advertisements_data,UnclaiColumns));
    /**
     * @param args the command line arguments
     */
  
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane AdvMode_panel;
    private javax.swing.JTextField ModeSerch_textBox;
    private javax.swing.JTable ModerMy_table;
    private javax.swing.JTable ModerUnclaim_table;
    private javax.swing.JButton approve_button;
    private javax.swing.JComboBox categ_comb_idd;
    private javax.swing.JButton claim_button;
    private javax.swing.JButton disapprove_button;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
